### ISSUE TITLE
update python can

### ISSUE THREAD

**Issue by mloebbert** [cruiten/Voron-Related#8]
Hi cruiten,

today I updated my Voron2.4 to canbus. Thank you for the great manual.

There is a minor issue in the doku:

> NOTE: If you receive an ImportError: No module named can error, then execute the following command to install the missing module: **sudo apt install python-can**

The correct command to install the missing python package is: **pip install python-can**

BR
Markus

**Comment by cruiten** [comment]
Thank you for raising this issue Markus.

The `sudo apt install python-can` command worked/works for me on my Raspberry Pi.

Is there any advantage to using the `pip install python-can` command?

I suppose that `pip` might be more system-agnostic than the `apt` command.

Please let me know.

Cor

**Comment by mloebbert** [comment]
Hi Cor,

I'm wondering installing python-can using apt works for you, may you double check that.

I tried it also on my Pi:

```
pi@mainsailos:~ $ sudo apt install python-can
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package python-can
```

Also the documentation on 'https://python-can.readthedocs.io/en/stable/installation.html' mentions the python package manager pip to install python-can.

Maybe you can add the pip call to your documentation as an alternative, if someone's system behaves like mine.

BR

Markus

**Comment by cruiten** [comment]
Interesting...

I just double-checked it on my system and as you can see it does not raise any errors:

<img width="522" alt="Screen Shot 2023-04-09 at 10 53 14 AM" src="https://user-images.githubusercontent.com/26015705/230788670-d84b8707-ee91-4128-869f-0f9a906df575.png">

However, I agree that it makes sense to add the pip call as an alternative...

Cor

**Comment by cruiten** [comment]
Updated documentation page with alternative way to install python-can.

Thanks you for the suggestion @mloebbert!

Cor
