### ISSUE TITLE
'GPIO25' is not a valid pin name on mcu 'SB2040'

### ISSUE THREAD

**Issue by wa2mze** [cruiten/Voron-Related#9]
I followed your instructions to set up the SB2040.  All seemed to work until I started working on the printer.cfg file.  I'm using the HV probe connector and I get the error "GPIO25 is not a valid pin name on mcu SB2040"  The line in the config file is 
pin:^SB2040:GPIO25
my  klippy.log is attached.  Looks like it could be a python software error in the version of klipper I'm using.
[klippy.log](https://github.com/cruiten/Voron-Related/files/14695553/klippy.log)

**Comment by cruiten** [comment]
The letters in the pin names for the SB2040 must be lower-case.

In other words, replace "GPIO25" with "gpio25" and you should be good to go.

**Comment by wa2mze** [comment]
Well that got me a little further.  Now getting this error with SB2040
"MCU 'SB2040' shutdown: oids already allocated"
[klippy (1).log](https://github.com/cruiten/Voron-Related/files/14711884/klippy.1.log)

**Comment by wa2mze** [comment]
Wait .... a soft reboot after updating printer.cfg didn't reset the toolhead board..  I did a power cycle, and it came up!
So, I guess there is a sw issue with the sb2040 not being able to be software reset after a config change.
